package ch.cern.todo.core.application.exception;

public class TaskCategoryNotFoundException extends NotFoundException {

    public TaskCategoryNotFoundException() {}

}
