package ch.cern.todo.core.application.exception;

public class TaskNotFoundException extends NotFoundException {

    public TaskNotFoundException() {}

}
