package ch.cern.todo.core.application.task.category.exception;

import ch.cern.todo.core.application.exception.NotFoundException;

public class TaskCategoryNotFoundException extends NotFoundException {

    public TaskCategoryNotFoundException() {}

}
